### ISSUE TITLE
AnimatorTextureBaker.cs/line32について

### ISSUE THREAD

**Issue by yarikomiVR** [sugi-cho/Animation-Texture-Baker#3]
上記のコードでanimator.speed = 0;となっており、フレーム0しかベイクできないようになっています。仕様でしょうか？

**Comment by yarikomiVR** [comment]
↑加えて、上記のスクリプトをアタッチしたオブジェクトがカメラ視野から外れるなど、アニメーション自体がカリングされるとベイクがうまくいかないようです。

**Comment by sugi-cho** [comment]
Line54において、第3引数に ` float normalizedTime`を設定しているので、forループ内でアニメーションを特定のフレームに進める処理をしています！

https://github.com/sugi-cho/Animation-Texture-Baker/blob/master/Assets/AnimationBaker/Scripts/AnimatorTextureBaker.cs#L56

https://docs.unity3d.com/ScriptReference/Animator.Play.html

**Comment by sugi-cho** [comment]
AnimatorTextureBakerは、Meshをカメラでレンダリングすることによって、テクスチャへの書き込みを行っているので、オブジェクトがカメラのレンダリング範囲内にある必要があります。
AnimationClipTextureBakerを使用すると、旧Animationでも、Animatorでも使えるので、おススメです！
