### ISSUE TITLE
[Feature Request] URP shader with specular - Env Reflections and SRP batcher support?

### ISSUE THREAD

**Issue by davoodkharmanzar** [sugi-cho/Animation-Texture-Baker#4]
it would be great if exists URP shader with specular - Env Reflections and SRP batcher support ...
thanks.

**Comment by sugi-cho** [comment]
I just add Shader Graph Example
https://github.com/sugi-cho/Animation-Texture-Baker/tree/master/Assets/ShaderGraph
![umaGraph](https://user-images.githubusercontent.com/346540/81478375-edf09b00-9257-11ea-9f4b-5ce73bee542b.gif)
