### ISSUE TITLE
 Broken vertex positions in Unity 2019.3.11

### ISSUE THREAD

**Issue by Tirarex** [sugi-cho/Animation-Texture-Baker#5]
I recently downloaded the repository and got broken horse animations, screenshot below. Baking animations does not help. The bird example works well.

![Unity_BBY6u5XXfR](https://user-images.githubusercontent.com/20671593/80948909-1285e680-8e04-11ea-91fa-6873e6f657e4.png)

**Comment by sugi-cho** [comment]
It seems that the vertex index on import has been changed by the version up of Unity.
Rebaking the texture will give you the correct texture.
This menu is confusing, though.

![bake_texture_menu](https://user-images.githubusercontent.com/346540/81262432-d5765a00-9078-11ea-8c00-a86d12d166d8.jpg)
