### ISSUE TITLE
hello. I encountered an error in my operation

### ISSUE THREAD

**Issue by platefacer** [sugi-cho/Animation-Texture-Baker#7]
I use unity version 2019.1.5f1. 

Compute shader (MeshInfoTextureGen): Property (OutTangent) at kernel index (0) is not set
UnityEngine.ComputeShader:Dispatch(Int32, Int32, Int32, Int32)
<Start>d__3:MoveNext() (at Assets/AnimationBaker/Scripts/AnimatorTextureBaker.cs:79)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by sugi-cho** [comment]
thank you!

[AnimationClipTextureBaker](https://github.com/sugi-cho/Animation-Texture-Baker/blob/master/Assets/AnimationBaker/Scripts/AnimationClipTextureBaker.cs) is working fine.

I will fix AnimatorTextureBaker and AnimationTextureBaker!

here is difference
- https://github.com/sugi-cho/Animation-Texture-Baker/blob/master/Assets/AnimationBaker/Scripts/AnimationClipTextureBaker.cs#L17-L22
- https://github.com/sugi-cho/Animation-Texture-Baker/blob/master/Assets/AnimationBaker/Scripts/AnimatorTextureBaker.cs#L16-L20

`AnimatorTextureBaker` does not bake TangentTexture. but ComputeShader has Tangent data.
